services:
  - type: web
    name: bollyfun
    env: python
    buildCommand: "./build.sh"
    # UPDATED: Use the new configuration file
    startCommand: "gunicorn --config gunicorn.conf.py BF.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: BF.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False


  - type: cron
    name: db-cleanup
    env: python
    # We use the same build command as the web service to ensure dependencies are installed
    buildCommand: "./build.sh" 
    # Command to run the Django management command
    startCommand: "python manage.py cleanup_db"
    # Schedule: 0 0 * * * runs at midnight (UTC) daily
    schedule: "0 0 * * *" 
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: BF.settings
      # It's crucial to pass the secret key so the command can access the DB
      - key: SECRET_KEY
        generateValue: true